name: Build Docker images
on:
  workflow_dispatch:

  push:
    branches:
      - master

concurrency: 
  group: ci-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 10
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ORG_GITHUB_TOKEN }}

      - name: Build and push (latest)
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: IMAGE=bitnami/redis:latest
          tags: ghcr.io/playtini/redis:latest
      
      - name: Build and push (latest)
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: IMAGE=bitnami/redis:stable
          tags: ghcr.io/playtini/redis:stable